{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Txn Staging\",\"Location Dim\",\"Txn\",\"Dataset Version\",\"Metadata\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.119.986.0 (23.07)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-IE",
    "cultures": [
      {
        "name": "en-IE",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Txn Staging",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\odhra\\Downloads\\COVID-19_HPSC_County_Statistics_Historic_Data.csv\"),[Delimiter=\",\", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"OBJECTID\", Int64.Type}, {\"ORIGID\", Int64.Type}, {\"CountyName\", type text}, {\"PopulationCensus16\", Int64.Type}, {\"TimeStamp\", type datetime}, {\"IGEasting\", Int64.Type}, {\"IGNorthing\", Int64.Type}, {\"Lat\", type number}, {\"Long\", type number}, {\"UGI\", type text}, {\"ConfirmedCovidCases\", Int64.Type}, {\"PopulationProportionCovidCases\", type number}, {\"ConfirmedCovidDeaths\", Int64.Type}, {\"ConfirmedCovidRecovered\", Int64.Type}, {\"SHAPE_Length\", type number}, {\"SHAPE_Area\", type number}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "42cbfdb0-1315-4112-b4b0-ce0fc2c9fb7b"
      },
      {
        "name": "Dataset Version",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Number"
          }
        ],
        "expression": "1.1 meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "c52ea9a5-7954-4e21-b252-cba159bd6030"
      }
    ],
    "relationships": [
      {
        "name": "fcd5a3a1-525e-4dad-8168-c4b840e6c8a0",
        "fromColumn": "TimeStamp",
        "fromTable": "Txn",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_baa7bd17-0998-4bb0-bc84-8e152b7ad0d4"
      },
      {
        "name": "f25624ad-07ed-4368-9202-6329fcb030a2",
        "fromColumn": "ORIGID",
        "fromTable": "Txn",
        "toColumn": "ORIGID",
        "toTable": "Location Dim"
      }
    ],
    "sourceQueryCulture": "en-IE",
    "tables": [
      {
        "name": "DateTableTemplate_4222ed15-5b0e-4797-b07e-3b003e945a4c",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "329dda7c-4387-4718-ae6a-452d41b61153",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "13b65187-84c0-40c3-afa6-bc0af4e54a44",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8249a0d7-6ad8-4436-a2dc-32474193e091",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a60ecc0d-6f07-4047-93e3-469fcae9c561",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "42aa6e71-6c4f-45e2-b446-89a60a745cac",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2f39101e-7842-4f52-bcdd-db52d106c3e5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f773e1dd-c0cd-48e1-bdb7-eb524c320be1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d1575491-a841-43e3-bca3-5b3b50802169",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a1e83d7b-3916-45e3-a860-0491b60c9f72",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0df373ca-60c8-4757-89f4-76654bf455ee",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d387ab08-f34d-4308-be2c-811f320452e1",
                "ordinal": 3
              }
            ],
            "lineageTag": "863a38c3-9dd9-4c73-872d-e47e7c1d1f69"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "e040a57c-b413-4348-bca7-bad2667c4cd9",
        "partitions": [
          {
            "name": "DateTableTemplate_4222ed15-5b0e-4797-b07e-3b003e945a4c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_baa7bd17-0998-4bb0-bc84-8e152b7ad0d4",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "53175b67-155f-4922-9737-44a32580e08f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cebb4481-360b-4ada-9b6e-d73f0a54cdb1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "13f56e7a-f166-4300-9302-c341a814f595",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8d7aaecb-69a7-44ca-839e-f77ea45e6242",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f9daf751-d050-4189-a923-3ddfaade8610",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ebf62683-5f7d-4ea5-9ef3-3bf86dd7b734",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d9142573-c36a-466b-89e7-516cdfba668c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d46347a4-68ff-410a-9e72-5e37c1a0dfaf",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e5811e59-d28f-4d92-8119-60dc6a57ad92",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "19ae79e7-3ffd-44bc-a8e9-06a1b422c23f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2087baf2-c4b7-41fe-8d87-71564dba0895",
                "ordinal": 3
              }
            ],
            "lineageTag": "cdebe3d6-33ab-4a32-acc7-adfac932054b"
          }
        ],
        "isHidden": true,
        "lineageTag": "1b5bc7f1-f6c9-4e5d-bf67-c0f7a4620241",
        "partitions": [
          {
            "name": "LocalDateTable_baa7bd17-0998-4bb0-bc84-8e152b7ad0d4",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Txn'[TimeStamp])), 1, 1), Date(Year(MAX('Txn'[TimeStamp])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Location Dim",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CountyName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "666dc34f-43f5-4019-ac28-e8b6f78bc002",
            "sourceColumn": "CountyName",
            "summarizeBy": "none"
          },
          {
            "name": "IGEasting",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ac60d2e5-30e1-4154-aaad-da86e6e6a571",
            "sourceColumn": "IGEasting",
            "summarizeBy": "none"
          },
          {
            "name": "IGNorthing",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fbe0e765-2607-488a-8b15-45520160c2a7",
            "sourceColumn": "IGNorthing",
            "summarizeBy": "none"
          },
          {
            "name": "Lat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "afeccad4-1efc-4b05-9624-b046bdc65f59",
            "sourceColumn": "Lat",
            "summarizeBy": "none"
          },
          {
            "name": "Long",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "316afcf8-f5fc-467d-b327-5ffafe6fdc42",
            "sourceColumn": "Long",
            "summarizeBy": "none"
          },
          {
            "name": "ORIGID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b5c4d8f-a4c1-4022-9549-375b91a299f5",
            "sourceColumn": "ORIGID",
            "summarizeBy": "none"
          },
          {
            "name": "SHAPE_Area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "30233395-333b-4389-94e8-599073d98938",
            "sourceColumn": "SHAPE_Area",
            "summarizeBy": "none"
          },
          {
            "name": "SHAPE_Length",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2a249e86-9d73-42a5-8cb0-9d4794c62e7e",
            "sourceColumn": "SHAPE_Length",
            "summarizeBy": "none"
          },
          {
            "name": "UGI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "673167df-51a2-49bc-9014-28d910c8d7a8",
            "sourceColumn": "UGI",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a5cf3b93-4867-4b47-929d-045bf0e75976",
        "partitions": [
          {
            "name": "Location Dim",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Txn Staging\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"ORIGID\", \"CountyName\", \"IGEasting\", \"IGNorthing\", \"Lat\", \"Long\", \"UGI\", \"SHAPE_Length\", \"SHAPE_Area\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\", {\"ORIGID\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Metadata",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Dataset Version",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "displayFolder": "Columns",
            "isHidden": true,
            "lineageTag": "44add4e5-c6f0-4e5c-bae6-258b93a0eb27",
            "sourceColumn": "Dataset Version",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ee896f93-167e-4c51-b921-d5a4d5b34388",
        "measures": [
          {
            "name": "DatasetVersion",
            "displayFolder": "Metadata",
            "expression": [
              "",
              "    MAX ( Metadata[Dataset Version] )"
            ],
            "lineageTag": "798aefd2-3f53-4c1d-bbf4-9fceae69e407"
          }
        ],
        "partitions": [
          {
            "name": "Metadata",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Dataset Version\",",
                "    #\"Converted to Table\" = #table(1, {{Source}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"Dataset Version\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Txn",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ConfirmedCovidCases",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Columns",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "afe16e39-157d-4143-9a14-0708f1501a4e",
            "sourceColumn": "ConfirmedCovidCases",
            "summarizeBy": "sum"
          },
          {
            "name": "ConfirmedCovidDeaths",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Columns",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "eb95c08d-99fb-4788-859e-b8fca0c75985",
            "sourceColumn": "ConfirmedCovidDeaths",
            "summarizeBy": "sum"
          },
          {
            "name": "ConfirmedCovidRecovered",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Columns",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cc721214-cb42-49e3-bc42-b8fa5b7b4e44",
            "sourceColumn": "ConfirmedCovidRecovered",
            "summarizeBy": "sum"
          },
          {
            "name": "OBJECTID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Columns",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1ef5f12e-541f-41cd-9bd6-ab2ceb3df2bf",
            "sourceColumn": "OBJECTID",
            "summarizeBy": "count"
          },
          {
            "name": "ORIGID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Columns",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5fbc8e0c-cf21-4614-81f8-761138391f78",
            "sourceColumn": "ORIGID",
            "summarizeBy": "none"
          },
          {
            "name": "PopulationCensus16",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Columns",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6a182647-82da-4935-94db-0591d87dbbb8",
            "sourceColumn": "PopulationCensus16",
            "summarizeBy": "sum"
          },
          {
            "name": "PopulationProportionCovidCases",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Columns",
            "isHidden": true,
            "lineageTag": "d8727bb9-9474-4c5f-9b08-e838611bf56b",
            "sourceColumn": "PopulationProportionCovidCases",
            "summarizeBy": "sum"
          },
          {
            "name": "TimeStamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "displayFolder": "Columns",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "98403e72-c2ac-403a-b91c-d2d617cf1d07",
            "sourceColumn": "TimeStamp",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_baa7bd17-0998-4bb0-bc84-8e152b7ad0d4"
                },
                "isDefault": true,
                "relationship": "fcd5a3a1-525e-4dad-8168-c4b840e6c8a0"
              }
            ]
          }
        ],
        "lineageTag": "26318ff4-0f19-4e10-8f94-050dd97e0489",
        "measures": [
          {
            "name": "Number of Cases",
            "displayFolder": "Measures",
            "expression": [
              "",
              "    SUM ( Txn[ConfirmedCovidCases] ) + 0"
            ],
            "formatString": "0",
            "lineageTag": "082439fc-b015-416a-a763-8581b7d34be8"
          }
        ],
        "partitions": [
          {
            "name": "Txn",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Txn Staging\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"OBJECTID\", \"ORIGID\", \"PopulationCensus16\", \"TimeStamp\", \"ConfirmedCovidCases\", \"PopulationProportionCovidCases\", \"ConfirmedCovidDeaths\", \"ConfirmedCovidRecovered\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}